### ISSUE TITLE
Big performance problems

### ISSUE THREAD

**Issue by jonom** [bluehousegroup/silverstripe-upgrade-notification#10]
Hi again! So I launched a new website and noticed it was really sluggish, even with all the caching I had in place. I removed this module and my page response times went from 2.05s to 87ms :)

The problem is in this module's _config.php - there is a bunch of code that shouldn't be there as it will be evaluated unnecessarily on every single request.

**Comment by andrewvt** [comment]
This should be all set.  I moved that code into an extension of UpgradeNotificationLeftAndMainExtension so it would only be called when in the admin.  Please let me know if this resolves the performance issue.

**Comment by andrewvt** [comment]
Closing for now, but feel free to reopen if you still have any issues.  Thanks!

**Comment by jonom** [comment]
Sweet, thanks Andrew
