### ISSUE TITLE
Allow customisation of messages

### ISSUE THREAD

**Issue by jonom** [bluehousegroup/silverstripe-upgrade-notification#6]
I would like to be able to customise the messages, for example change "Your SilverStripe is out of date" to "A newer version of SilverStripe is available", and change the paragraph below as well to better suit my own clients.

One approach might be render all the content with a template, then people could just override the template to change any part of the content to suit them. Another idea would be to use the config system to set the messages. I see you've added an extension hook which is cool so I guess I could update the form that way too but would just be trickier :)

**Comment by andrewvt** [comment]
Customizing of messaging available in config yml as requested see README.md.
