### ISSUE TITLE
Model changes

### ISSUE THREAD

**Issue by jonom** [bluehousegroup/silverstripe-upgrade-notification#8]
Is there a reason `UpgradeNotification` extends `DataExtension`? I see you're extending DataObject with this extension but I don't see any reason to do that - that will add all of your UpgradeNotification code to all sub-classes of DataObject.

I think you could probably combine the `UpgradeNotificationPage` and `UpgradeNotification` classes in to one and just have `UpgradeNotification extends LeftAndMain`.

Thanks for implementing all those other suggestions already!

**Comment by andrewvt** [comment]
I agree, some consolidation can definitely happen at this point.

**Comment by andrewvt** [comment]
Classes consolidated down into one and generally cleaned up.
